import cspellPlugin from '@cspell/eslint-plugin'
import nxPlugin from '@nx/eslint-plugin'
import * as typescriptParser from '@typescript-eslint/parser'
import prettierConfig from 'eslint-config-prettier'

/**
 * The ESLint layer, reduced to the four rules oxlint cannot own.
 *
 * Everything else moved to `@bluetel-ai/oxlint-config`, which runs the other 142 of the 146
 * enforced rules — including all 41 type-aware ones — in a fraction of the time. The counts
 * come from `specs/005-oxlint-lint-performance/rule-inventory.md`, which is generated from
 * both layers' real configs by `pnpm lint-inventory`; if they disagree with this comment,
 * the generated file is right. What is left here is only what has nowhere else to go:
 *
 * - `@nx/enforce-module-boundaries` needs the Nx project graph, which exists only inside an
 *   Nx invocation. (It was silently skipped on the old staged-file path for exactly that
 *   reason — `No cached ProjectGraph is available. The rule will be skipped.` Running it as
 *   an Nx target is what finally makes it fire.)
 * - `@cspell/spellchecker` has no oxlint equivalent and costs ~1555 ms per invocation, none
 *   of which scales with the number of files being checked.
 * - `no-octal` and `no-dupe-args` are the two core ESLint rules in this workspace's set that
 *   oxlint does not implement. Established by probing, not assumed: oxlint fails config
 *   parsing on an unknown rule name, so every rule was tested by writing a config that
 *   enables it. Both only ever fire on sloppy-mode scripts — a legacy octal literal and a
 *   duplicate parameter name are strict-mode syntax errors — which is why `no-dupe-args` is
 *   one of the rules typescript-eslint switches off for TypeScript, and why both fixtures in
 *   `tooling/lint-coverage` are `.cjs`.
 *
 * This config is run once per project by the Nx `lint-workspace` target — cached,
 * `affected`-scoped, and never per-file.
 *
 * It still needs `@typescript-eslint/parser` to read `.ts` files at all — the rules that still
 * apply to TypeScript files have to see an AST. That is *parsing*, not type-checking:
 * no `parserOptions.project`, no program construction, no `strictTypeChecked`. It does still
 * mean this layer imports `typescript`, so FR-021 is met in substance but not to the letter,
 * and the TypeScript 7 phase will need either a parser that does not (`eslint-parser-oxc`)
 * or typescript-eslint's TS 7 support, whichever lands first. Recorded rather than glossed:
 * the per-file gate is free of it, which is what the performance work needed, but the
 * workspace gate is not.
 *
 * Usage in a project's eslint.config.mjs:
 *   import { workspaceChecks } from '@bluetel-ai/eslint-config-internal'
 *   export default workspaceChecks
 */
export const workspaceChecks = [
  // image-sources.ts uses require() for asset imports — incompatible with strict TS/module rules
  { ignores: ['**/image-sources.ts'] },
  // importMap.js is auto-generated by Payload CMS — skip all linting
  { ignores: ['**/importMap.js'] },
  // The lint-coverage fixtures are planted rule violations, materialised at test time
  { ignores: ['**/tooling/lint-coverage/fixtures/**'] },
  {
    plugins: { '@nx': nxPlugin },
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx', '**/*.mjs', '**/*.cjs'],
    ignores: ['**/*.config.{js,mjs,cjs,ts,mts,cts}'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          allow: [],
          depConstraints: [{ sourceTag: '*', onlyDependOnLibsWithTags: ['*'] }],
        },
      ],
    },
  },
  {
    files: ['**/*.{ts,tsx,mts,cts}'],
    languageOptions: { parser: typescriptParser },
  },
  {
    files: ['**/*.{js,jsx,mjs,cjs,ts,tsx}'],
    plugins: { '@cspell': cspellPlugin },
    rules: {
      '@cspell/spellchecker': ['error', {}],
      'no-octal': 'error',
      'no-dupe-args': 'error',
    },
  },
  // Must be last — disables ESLint rules that would conflict with Prettier formatting
  prettierConfig,
]
