/**
 * PR manager for bookkeeping and verification.
 *
 * Records branch-to-issue mappings in the Branch_Map after Kiro CLI
 * completes, and verifies that Kiro CLI has pushed commits to the
 * remote branch. Does NOT perform git add, commit, push, or PR
 * creation — the Kiro CLI is responsible for all git operations and
 * PR lifecycle.
 *
 * Factory function `createPRManager` returns `recordBranch` and
 * `verifyPushedCommits` functions bound to the given config and logger.
 *
 * `formatPRTitle` and `formatPRBody` helpers are retained for use by
 * the prompt builder (to construct PR title/body instructions in prompts).
 */

import { execFile as execFileCb } from 'node:child_process'
import { promisify } from 'node:util'

import type pino from 'pino'

import type { BranchMapInstance } from './branch-map'
import { renderBranchName } from './branch-template'

const execFile = promisify(execFileCb)

// ── Config ──────────────────────────────────────────────────────────

export interface PRManagerConfig {
  branchTemplate: string
}

// ── Helpers ─────────────────────────────────────────────────────────

/**
 * Formats the PR title from an issue title.
 *
 * @internal Exported for testing (Property 14) and prompt builder usage.
 */
export const formatPRTitle = (issueTitle: string): string => `[Kiro] ${issueTitle}`

/**
 * Formats the PR body with a closing reference to the issue.
 *
 * @internal Exported for testing (Property 14) and prompt builder usage.
 */
export const formatPRBody = (issueNumber: number): string =>
  `Closes #${String(issueNumber)}\n\nThis pull request was automatically generated by Rocky.`

// ── Factory ─────────────────────────────────────────────────────────

/**
 * Creates a PR manager bound to the given config and logger.
 *
 * The PR manager is a thin bookkeeping layer:
 * - `recordBranch`: renders branch name from template, stores in Branch_Map
 * - `verifyPushedCommits`: fetches from origin and checks for new commits
 *
 * @param config - Branch template configuration
 * @param logger - Pino logger instance for structured logging
 * @returns Object with `recordBranch` and `verifyPushedCommits` functions
 */
export const createPRManager = (
  config: PRManagerConfig,
  logger: pino.Logger,
): {
  recordBranch: (params: {
    repoFullName: string
    issueNumber: number
    issueTitle: string
    branchMap: BranchMapInstance
  }) => { branchName: string }
  verifyPushedCommits: (params: {
    repoFullName: string
    branchName: string
    workingDir: string
  }) => Promise<boolean>
} => {
  /**
   * Records a branch mapping in the Branch_Map.
   *
   * Renders the branch name from the configured template using the
   * issue number and title, stores it in the Branch_Map, and returns
   * the rendered branch name. No git operations are performed.
   */
  const recordBranch = (params: {
    repoFullName: string
    issueNumber: number
    issueTitle: string
    branchMap: BranchMapInstance
  }): { branchName: string } => {
    const { repoFullName, issueNumber, issueTitle, branchMap } = params
    const log = logger.child({ repo: repoFullName, issueNumber, step: 'record-branch' })

    // Render branch name from template
    const branchName = renderBranchName(config.branchTemplate, {
      issueNumber,
      issueTitle,
    })
    log.info({ branchName }, 'Rendered branch name from template')

    // Record branch in Branch_Map
    branchMap.set(repoFullName, issueNumber, branchName)
    log.debug('Branch recorded in Branch_Map')

    return { branchName }
  }

  /**
   * Verifies that Kiro CLI has pushed new commits to the remote branch.
   *
   * Runs `git fetch origin` and checks if the remote branch exists with
   * commits. Returns true when the remote branch has commits, false otherwise.
   */
  const verifyPushedCommits = async (params: {
    repoFullName: string
    branchName: string
    workingDir: string
  }): Promise<boolean> => {
    const { repoFullName, branchName, workingDir } = params
    const log = logger.child({ repo: repoFullName, branchName, step: 'verify-pushed-commits' })

    try {
      // Fetch latest state from origin
      await execFile('git', ['fetch', 'origin'], { cwd: workingDir })
      log.debug('Fetched latest state from origin')

      // Check if the remote branch exists and has commits
      try {
        const { stdout } = await execFile('git', ['rev-parse', `origin/${branchName}`], {
          cwd: workingDir,
        })
        const sha = stdout.trim()

        if (sha) {
          log.info({ sha, branchName }, 'Remote branch has commits')
          return true
        }

        log.info({ branchName }, 'Remote branch has no commits')
        return false
      } catch {
        log.info({ branchName }, 'Remote branch does not exist after fetch')
        return false
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      log.warn({ error: message }, 'Failed to verify pushed commits')
      return false
    }
  }

  return { recordBranch, verifyPushedCommits }
}
